services:
  - type: web
    name: brasil-burger
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
