// <auto-generated />
using System;
using BrasilBurgerC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrasilBurgerC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220232539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrasilBurgerC.Models.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prix")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Burgers");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telephone")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("integer");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeCommande")
                        .HasColumnType("integer");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LivreurId");

                    b.HasIndex("NumeroCommande")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.CommandeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BurgerId")
                        .HasColumnType("integer");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComplementId")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("PrixUnitaire")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BurgerId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ComplementId");

                    b.HasIndex("MenuId");

                    b.ToTable("CommandeItems");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Complement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prix")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Complements");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Livreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Livreurs");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoissonId")
                        .HasColumnType("integer");

                    b.Property<int>("BurgerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstArchive")
                        .HasColumnType("boolean");

                    b.Property<int?>("FritesId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoissonId");

                    b.HasIndex("BurgerId");

                    b.HasIndex("FritesId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstValide")
                        .HasColumnType("boolean");

                    b.Property<int>("ModePaiement")
                        .HasColumnType("integer");

                    b.Property<int>("Montant")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroTransaction")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prix")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrixLivraison")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Commande", b =>
                {
                    b.HasOne("BrasilBurgerC.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurgerC.Models.Livreur", "Livreur")
                        .WithMany("Commandes")
                        .HasForeignKey("LivreurId");

                    b.HasOne("BrasilBurgerC.Models.Zone", "Zone")
                        .WithMany("Commandes")
                        .HasForeignKey("ZoneId");

                    b.Navigation("Client");

                    b.Navigation("Livreur");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.CommandeItem", b =>
                {
                    b.HasOne("BrasilBurgerC.Models.Burger", "Burger")
                        .WithMany()
                        .HasForeignKey("BurgerId");

                    b.HasOne("BrasilBurgerC.Models.Commande", "Commande")
                        .WithMany("Items")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurgerC.Models.Complement", "Complement")
                        .WithMany("CommandeItems")
                        .HasForeignKey("ComplementId");

                    b.HasOne("BrasilBurgerC.Models.Menu", "Menu")
                        .WithMany("CommandeItems")
                        .HasForeignKey("MenuId");

                    b.Navigation("Burger");

                    b.Navigation("Commande");

                    b.Navigation("Complement");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Livreur", b =>
                {
                    b.HasOne("BrasilBurgerC.Models.Zone", "Zone")
                        .WithMany("Livreurs")
                        .HasForeignKey("ZoneId");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Menu", b =>
                {
                    b.HasOne("BrasilBurgerC.Models.Complement", "Boisson")
                        .WithMany()
                        .HasForeignKey("BoissonId");

                    b.HasOne("BrasilBurgerC.Models.Burger", "Burger")
                        .WithMany()
                        .HasForeignKey("BurgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurgerC.Models.Complement", "Frites")
                        .WithMany()
                        .HasForeignKey("FritesId");

                    b.Navigation("Boisson");

                    b.Navigation("Burger");

                    b.Navigation("Frites");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Paiement", b =>
                {
                    b.HasOne("BrasilBurgerC.Models.Commande", "Commande")
                        .WithOne("Paiement")
                        .HasForeignKey("BrasilBurgerC.Models.Paiement", "CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Commande", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Complement", b =>
                {
                    b.Navigation("CommandeItems");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Livreur", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Menu", b =>
                {
                    b.Navigation("CommandeItems");
                });

            modelBuilder.Entity("BrasilBurgerC.Models.Zone", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Livreurs");
                });
#pragma warning restore 612, 618
        }
    }
}
